<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Commons\Commons.CleanArchitechture\Commons.Domain.csproj" />
    <ProjectReference Include="..\..\Commons\Commons.Domain\Commons.Domain.csproj" />
  </ItemGroup>

</Project>
